---
title: "What even is Hyperpop?"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
```

### Homework week 9

```{r}
library(tidyverse)
library(spotifyr)
library(compmus)

####### HOLLYWOOD BABY
baby <-
  get_tidy_audio_analysis("48ElaQLYuOaybqagIlPxpU") |> # Hollywood Baby
  compmus_align(bars, segments) |>                     # Change `bars`
  select(bars) |>                                      #   in all three
  unnest(bars) |>                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
          compmus_summarise, pitches,
          method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) |>
  mutate(
    timbre =
      map(segments,
          compmus_summarise, timbre,
          method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )
baby |>
  compmus_gather_timbre() |>
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic()

####### SPOILED LITTLE BRAT
brat <-
  get_tidy_audio_analysis("724utiMbqUfT1g3tqbfQYu") |> # 
  compmus_align(bars, segments) |>                     # Change `bars`
  select(bars) |>                                      #   in all three
  unnest(bars) |>                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
          compmus_summarise, pitches,
          method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) |>
  mutate(
    timbre =
      map(segments,
          compmus_summarise, timbre,
          method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )
brat |>
  compmus_gather_timbre() |>
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic()

###### SELF SIMILARITY 

tape <-
  get_tidy_audio_analysis("4zOfSQJhPaHVdNIPrOJJVl") |> # 
  compmus_align(bars, segments) |>                     # Change `bars`
  select(bars) |>                                      #   in all three
  unnest(bars) |>                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
          compmus_summarise, pitches,
          method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) |>
  mutate(
    timbre =
      map(segments,
          compmus_summarise, timbre,
          method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )

tape |>
  compmus_self_similarity(timbre, "cosine") |> 
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = xduration,
      y = ystart + yduration / 2,
      height = yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_fixed() +
  scale_fill_viridis_c(guide = "none") +
  theme_classic() +
  labs(x = "", y = "")

```

***

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/48ElaQLYuOaybqagIlPxpU?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
For 


### Hyperpop is loud and energetic

```{r}
library(tidyverse)
library(spotifyr)
library(plotly)
library(dplyr)

# Track info from the tracks in the Hyperpop playlist
hyper <- get_playlist_audio_features("", "4fg8XveWZ4xQatc4mHLsyb")
classic <- get_playlist_audio_features("", "3WWGBxHe4bAyKFq1DAnszd")
sleepy <- get_playlist_audio_features("", "1hUOz9Cb5ELjJrLytD0n1b")
perfect <- get_playlist_audio_features("", "6MXc6iTKELyEL62ahBY2i2")
music2 <- get_playlist_audio_features("", "1GPov4sutwV2VRK7TB2y22")
feed <- get_playlist_audio_features("", "7oEgNy93qnlcm361HgrXrN")
umru <- get_playlist_audio_features("", "1Gh40BPKoYlLfQaGAisWjo")
sound <-get_playlist_audio_features("", "7DrJ92Lc9UaVB1rKM2UGsg")
goop <-get_playlist_audio_features("", "2eHpU1UvXMr8vSrb1p0fRz")
form <-get_playlist_audio_features("", "4w3jVLtbQufq1jCMBzlqOr")

corpus <-
  bind_rows(
    hyper |> mutate(category = "Hyperpop (Spotify editorial)"),
    classic |> mutate(category = "Hyperpop Classics (Spotify editorial)"),
    sleepy |> mutate(category = "Sleepy Zone (Community selection)"),
    perfect |> mutate(category = "Perfect Music Friday (Label picks)"),
    music2 |> mutate(category = "Music2 (Personal picks)"),
    feed |> mutate(category = "feedBack (Spotify editorial)"),
    umru |> mutate(category = "umru's Hard Listening (Artist picks)"),
    sound |> mutate(category = "The Sound of Hyperpop"),
    goop |> mutate(category = "Goop House Artists (Community selection)"),
    form |> mutate(category = "Every FORM All Nighter song")
    )


  ggplot(corpus, aes(x = energy, y = loudness, alpha = tempo, color = category, text = track.name)) +
  geom_point(size = 2, fill = "black") +

  scale_color_brewer(
    type = "qual",
    palette = "Spectral",
    name = "Playlist"
    ) +
    scale_alpha_continuous(
      guide = "none"
    )
    
ggplotly()
```

